version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mynetwork
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-nginx.conf:/etc/nginx/conf.d/laravel.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - mynetwork

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  #mailhog:
    #image: 'mailhog/mailhog:latest'
    #ports:
        #- '${FORWARD_MAILHOG_PORT:-1025}:1025'
        #- '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    #networks:

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
